### ISSUE TITLE
リファマイニングの説明をマイニングページに追加する

### ISSUE THREAD

**Issue by Odacchi** [Odacchi/fcoin-user-manual#10]
引用先として以下を添えて本家に飛べるようにした方がいい。

https://www.fcon.com/invite

**Comment by YOUFCoin** [comment]
リンクは間違えた！w
正解：https://www.fcoin.com/invite

**Comment by Odacchi** [comment]
プルリク作ったので参考に中国語翻訳をお願いしたい！
https://github.com/Odacchi/fcoin-user-manual/pull/18/files

**Comment by Odacchi** [comment]
スピード重視ということでもう本番にあげちゃった！

中国語ページに日本語が混ざってる状態なので、翻訳待ちです。

**Comment by Odacchi** [comment]
翻訳済みなのでクローズします。
問題あれば、別途issueたてましょう。
