### ISSUE TITLE
トップページのFTについての説明を更新する

### ISSUE THREAD

**Issue by Odacchi** [Odacchi/fcoin-user-manual#12]
Fractalチェーンに移行したので、見直しが必要

**Comment by KouBT** [comment]
*元はプラットフォームFCoinが発行したプラットフォームトークンですが、パブリックチェーンのリリースにより、パブリックチェーントークンにアップデートされました。

**Comment by Odacchi** [comment]
FCoin取引所の取引所トークンでしたが、独自チェーンのFractal（フラクタル）チェーンのリリースにより、パブリックチェーントークンにアップデートされました。

**Comment by Odacchi** [comment]
https://github.com/Odacchi/fcoin-user-manual/compare/feature/update-explanation-of-ft-on-top-page?expand=1

**Comment by YOUFCoin** [comment]
> これでどうかな？
> 
> > FCoin取引所の取引所トークンでしたが、独自チェーンのFractal（フラクタル）チェーンのリリースにより、パブリックチェーントークンにアップデートされました。
> 
> あと、「ブロックチェーンエクスプローラー」の「エクスプローラー」の中国語も知りたい！

**Comment by YOUFCoin** [comment]
FCoin取引所の取引所トークンでしたが、独自チェーンのFractal（フラクタル）チェーンのリリースにより、パブリックチェーントークンにアップデートされました。

**Comment by YOUFCoin** [comment]
FCoin取引所の取引所トークンでしたが、独自チェーンのFractal（フラクタル）チェーンのリリースにより、パブリックチェーントークンにアップデートされました。

**Comment by YOUFCoin** [comment]
FCoin取引所の取引所トークンでしたが、独自チェーンのFractal（フラクタル）チェーンのリリースにより、パブリックチェーントークンにアップデートされました。　　　　　　　　　　　　　
通訳：
FT起初是FCoin的平台币，作为社区化交易平台FCoin的权益代表。
随着Fractal项目的启动，FCoin Token正式升级为FToken，其本身也从“平台币”升级为“公链币”。

**Comment by Odacchi** [comment]
開発中のコードです。

プルリクエスト（プルリク）：
https://github.com/Odacchi/fcoin-user-manual/pull/13/files

**Comment by Odacchi** [comment]
本番アップ済みのためこのイシュークローズします。
