### ISSUE TITLE
トリセツ通訳の修正

### ISSUE THREAD

**Issue by YOUFCoin** [Odacchi/fcoin-user-manual#14]
既にアップされた通訳の内容にある問題（文法、当て字など）を発見し修正しましょ

**Comment by YOUFCoin** [comment]
「3分でFCoinのサービスを理解する」のボードで以下のように修正します。
FCoin是什么？
FCoin是中国的数字货币交易所，由火币原CTO张健先生创设。同时中国最大的区块链信息专业服务平台火星财经持有1亿FT使得FCoin倍具话题性。作为加密行业的先驱者，FCoin发明/装载了现如今多数交易所采用的下列概念：

**Comment by YOUFCoin** [comment]
*挖矿详解也有所提及，
FCoin Fund每周五会将该周分红用于回购销毁， 由于这种机制的存在，FT是一种总发行量在逐渐减少的通缩型数字资产。

**Comment by YOUFCoin** [comment]
分红制度

通过用户在交易所交易，FCoin平台可以获得手续费收益。
其中20%用于支持平台开支维持，80%将分配给FT持有者。
每日平台收益的使用途径如下图所示。

**Comment by YOUFCoin** [comment]
关于挖矿
通过在交易所交易，将获得交易所平台币FT。 作为创造了这样的“交易挖矿”模式，进而广为人知的交易所FCoin， 现在将被改良、向着“日常使用FCoin就是参与FT的挖矿”而前进。

**Comment by YOUFCoin** [comment]
理财账户（Financial account）で
需要注意的一点是，存在各币种一天之内仅能充值或提现一次的限制。 该限制会在每天早上8点（北京时间）重置。

**Comment by Odacchi** [comment]
ここに書いてある内容は修正し反映したのでクローズします。
もし問題が見つかれば再度チケットを作りましょう！
