### ISSUE TITLE
よくある質問の通訳

### ISSUE THREAD

**Issue by YOUFCoin** [Odacchi/fcoin-user-manual#16]
首页

Q. 注册时页面显示「invalid password」。
A. 参考空栏里的提示。（请仔细阅读！） 8～32文字，至少包含一个大写字母，小写字母，数字，特殊符号（~!@#$%^&*()_+）。

Q. 不做KYC的话会有什么影响
A. 更改密码的提现额度上有限制。 此外，如果已完成KYC，在遇到提现问题时将有助于顺利的得到处理，所以强烈建议申请KYC。

充值和提现的时间和限制

Q. 如何获得分红？
A. 买入FT并锁仓（任何形式的锁仓都可以，一般为活期锁仓和定期锁仓）
网页的锁仓方法 
APP的锁仓方法
Q. 分红什么时候？
A. FT锁仓的第二天。
关于分红机制（电报）
Q.如何确认分红已到账
A. 财务明细-我的钱包-收入分配

Q. 手机提现的时候无法输入地址
A. 虽然可以正常复制和粘贴，但最好提前保存地址然后提现。 我的钱包-提现-添加提现地址。
Q. 想取消提现
A. 如果未按下提现确认电子邮件中的链接，可以在提现历史中取消。

如果还有疑问的话，请在下方的电报群进行提问。志愿者会进行回答。
FCoin疑问群（电报）

**Comment by Odacchi** [comment]
アップロード済みです。チェックして問題なければCloseして下さい−！

https://www.fcoin-manual.com/cn/faq.html

**Comment by KouBT** [comment]
Q. 注册页面出现「invalid password」，无法继续。
A. 要求记载在密码栏下。（请仔细阅读） 8～32字、至少需要1个小写字母、一个大写字母、和一个数字。
のところで、

Q. 注册页面出现「invalid password」，无法继续。
A. 要求记载在密码栏下。（请仔细阅读） 8～32字、至少需要一个小写字母、一个大写字母、和一个数字。

**Comment by KouBT** [comment]
これ以外、問題なし！訂正したら、クローズしてください。

**Comment by Odacchi** [comment]
修正済のためクローズ
