### ISSUE TITLE
トリセツ内の誤字脱字。ルール変更に伴う文章改定必要箇所

### ISSUE THREAD

**Issue by GSHT007** [Odacchi/fcoin-user-manual#17]
ここで既にupされているトリセツの誤字脱字を掲載します

**Comment by GSHT007** [comment]
よくある質問の中の誤字脱字

**Comment by GSHT007** [comment]
Q. 登録の画面で「invalid password」と出てき進めないです。
→Q. 登録の画面で「invalid password」と出て**来て**進めないです。

**Comment by GSHT007** [comment]
Q. KYCに必要な書類はなんですか？
A. パスポートや、免許でできます。
→Q. KYCに必要な書類はなんですか？
A. パスポートや、**運転免許証**でできます。

**Comment by GSHT007** [comment]
Q. 配当はどうすればもらえますか？
A. FTを購入し、ロックアップ（タイプは「Dividend Lock-up」を選択）することでもらえます。
→Q. 配当はどうすればもらえますか？
A. FTを購入し、ロックアップ（タイプは「Dividend Lock-up」**もしくは「fixed term」**を選択）することでもらえます。

**Comment by GSHT007** [comment]
3分でFCoinのサービスを理解する。のページの最後

FTロックアップマイニング
FTをロックアップしておくと毎日の配当とは別にFTが配布される
→FTロックアップマイニング
FTをfixed termでロックアップしておくと毎日の配当とは別にFTが配布される

**Comment by Odacchi** [comment]
よくある質問に関してはテレグラムの文言のまんまコピペなのでしたw　ありがたい！！

**Comment by Odacchi** [comment]
一通り改修しましたー！
問題なさそうであれば、issueクローズしちゃってくださいー！
（コメントするときにClose and commentボタンを押せば良さそう）

**Comment by onizkn** [comment]
3分でわかるfcoinのところのレバレッジの説明の箇所  最大5倍になってるので6倍に変更したほうがいいと思います。

**Comment by GSHT007** [comment]
おだっちさん上の鬼さんのよろしくー

**Comment by Odacchi** [comment]
完了！

**Comment by Odacchi** [comment]
2019 6/26時点までで必要な分は一通り対応済みということでクローズします！

またアップデートがあれば、再度issueたてましょう！
