### ISSUE TITLE
マイニング詳細でロックアップマイニングの参加条件と開設の修正

### ISSUE THREAD

**Issue by BlueKanbu** [Odacchi/fcoin-user-manual#22]
「項目 | 説明
-- | --
参加方法 | FTをロックアップし、24時間以上が経過
参加条件 | 全員参加可能
FTの付与タイミング | 毎日（日本時間の深夜1:00締め）」

「FTをFixed-termでロックアップしておくと毎日の配当とは別にFTが配布されます。 ロックアップタイプによって、マイニングの効率が異なり、期間が長いほどマイニング効率が上がります。
具体的には、通常のロックアップに比べ、下記の図で算出される係数倍の量のFTが貰えるようになります。」

と書いているし、事実と少し差がある。

**Comment by BlueKanbu** [comment]
例えば、「Fixed-term」だけではなく、マイニング報酬、コミュニティ推薦者、OTCサービスプロバイダー、認証機関などのロックアップタイプもロックアップマイニングの対象となる。

**Comment by BlueKanbu** [comment]
開設の方は、
fixable 以外でFTをロックアップするで参加できます（「Fixed-term」だけではなく、マイニング報酬、コミュニティ推薦者、OTCサービスプロバイダー、認証機関も含む）。FTを上記のタイプでロックアップしておくと毎日の配当とは別にFTが配布されます。 ロックアップタイプによって、マイニングの効率が異なり、期間が長いほどマイニング効率が上がります。

具体的には、通常のロックアップに比べ、下記の図で算出される係数倍の量のFTが貰えるようになります。

**Comment by Odacchi** [comment]
日本語版は対応したのでクローズします。
（中国語翻訳は別のissueとして作成 #26
