### ISSUE TITLE
取引マイニングのアップデート対応の中国語翻訳

### ISSUE THREAD

**Issue by Odacchi** [Odacchi/fcoin-user-manual#25]
以下翻訳お願いします（前半部分はほとんど今のと変わりません）。

--- 

特定の通貨ペアで取引が成立すると、出来高への貢献度に応じて、翌日マイニング報酬のFTが付与されます。  
一日あたりのマイニング総生産量が通貨ペアごとに決まっており、定期的に生産量の見直しがされます。  
基本的には各通貨ペアごとの出来高に対し、自身が当該通貨ペアで貢献した出来高の割合が、翌日付与されるFTの量となります。  

取引マイニングは2つの部分にわかれており、FTのマイニング量はそれぞれ計算式によって見積もることが可能です。

- 一日の総取引量に対する自分の取引量
```
一日のFTマイニング量 = 当該通貨ペアの一日のFT総生産量 ✕ 0.5 ✕ (当該通貨ペアで自身が貢献した出来高 / 当該通貨ペアの出来高)
```

- 一分単位の総取引量に対する自分の取引量
```
1分単位のFTマイニング量 = 当該通貨ペアの一日のFT総生産量 ✕ 1/2880 ✕ (当該通貨ペアで自身が1分間で貢献した出来高 / 当該通貨ペアの1分間の出来高)
```

![取引マイニングのアルゴリズム](./images/mining/trade-mining-algorithm.jpg "取引マイニングのアルゴリズム")

具体的なマイニング量の計算例は下記の通りです。
![取引マイニングの具体例](./images/mining/trade-mining-example.jpg "取引マイニングの具体例")

**Comment by YOUFCoin** [comment]
在指定交易对成交，根据对交易额的贡献程度，次日会发放挖矿返还部分的FT。
交易对不同，当日的挖矿额度不同，而且定期会调整挖矿额度。
根据用户所贡献的交易额占各个交易对的交易额的比重，计算最终所发放的FT挖矿返还的数量。
挖矿所能获得的FT返还，大抵可以通过下列公式进行计算。（分为两部分）

按照一整天中对于交易总额的贡献程度
次日发放的FT ≒ 该交易对每日挖矿额度 ✕50%  ✕(用户在该交易对贡献的交易量 / 该交易对交易总量)

按照每一分钟对于这一分钟内交易额的贡献程度
次日发放的FT ≒ 该交易对每日挖矿额度 ✕1/2880  ✕(用户在一分钟内对该交易对贡献的交易量 / 该交易对一分钟内的交易总量)

**Comment by Odacchi** [comment]
本番に反映されたのでクローズします。
