### ISSUE TITLE
ロックアップマイニングの説明を見直した箇所の中国語翻訳

### ISSUE THREAD

**Issue by Odacchi** [Odacchi/fcoin-user-manual#26]
お願いします。

### 解説
Flexible（旧Dividend）タイプ以外のロックアップタイプでFTをロックアップすることで参加できます
（「Fixed-term」だけではなく、マイニング報酬、コミュニティ推薦者、OTCサービスプロバイダー、認証機関も含む）。  
FTを上記のタイプでロックアップしておくと毎日の配当とは別にFTが配布されます。 
ロックアップタイプによって、マイニングの効率が異なり、期間が長いほどマイニング効率が上がります。  
具体的には、通常のロックアップに比べ、下記の図で算出される係数倍の量のFTが貰えるようになります。

**Comment by YOUFCoin** [comment]
解说

活期锁仓（以前的分红锁仓）形式以外的锁仓类型（定期锁仓，社区推荐者，OTC商家，保荐机构）都能参加锁仓挖矿。
按照以上类型进行锁仓FT的话，就会获得每日分红收益和锁仓挖矿返还。（分别发放）
锁仓类型不同，挖矿的效率也不同。但是总体上为，锁仓的时间越长，挖矿效率就越高，获得的FT返还就越多。
具体，各个锁仓时间和效率（挖矿系数）的对应关系如下图。

**Comment by Odacchi** [comment]
本番に反映させたのでクローズします。
