### ISSUE TITLE
マイニングの産出のうち、ロックアップされない一定割合のFTについての記述が必要

### ISSUE THREAD

**Issue by Odacchi** [Odacchi/fcoin-user-manual#27]
マイニングページ少し見直さないといけない。とりあえずissueだけつくっておきます。

**Comment by Odacchi** [comment]
翻訳お願いします！

---

マイニングするとFTが付与されますが、そのうちの一定割合（下記の図参照）は、1年ロックアップ*された状態で付与されます。  
今後、半減期（後述）が来るたびに、マイニングで産出されるFTは減っていきますが、ロックアップされないまま付与されるFTの割合は増えていきます。

**Comment by BlueKanbu** [comment]
参与挖矿，即可获得FT。其中，有一定的比例（参照下图）会以锁仓一年*的状态发放。
今后，每次迎来半减期（其后详细记述）时，虽然挖矿产出的FT会减少，但是未锁仓状态直接发放的FT所占的比例会逐渐增加。

**Comment by Odacchi** [comment]
ありがとう！対応したのでクローズします。
