### ISSUE TITLE
手数料体系の変更のアップデート

### ISSUE THREAD

**Issue by Odacchi** [Odacchi/fcoin-user-manual#30]
日本語版と中国語版の画像のアップデート

**Comment by Odacchi** [comment]
下記の中国語翻訳お願いできますか
---

メインボードAは完全無料です。
メインボードBと革新ボードは、maker側がマイナス手数料で、taker側が手数料を払い、
差し引きで残った分が、プラットフォームの収益となります。  
FOneは売り手側にだけ手数料がかかる料金体系となっています。

**Comment by GSHT007** [comment]
主板A完全免费。
主板B和创新板上，主动吃支付手续费，挂单被动成交赚取手续费
剩余的余额是平台收入。
FOne上只有卖家需要支付手续费。

**Comment by Odacchi** [comment]
反映しました！

**Comment by BlueKanbu** [comment]
主板A完全免费。
在主板B和创新板交易，Maker（挂单被动成交）可以赚取手续费，Taker（主动吃单）支付手续费，差额部分为平台收入。
FOne上，只有卖方需要支付手续费。

**Comment by BlueKanbu** [comment]
少しだけ表現を変えました。お願いします。

**Comment by Odacchi** [comment]
反映しましたー！のでクローズします。
