### ISSUE TITLE
直近板並べマイニングのアップデート対応

### ISSUE THREAD

**Issue by Odacchi** [Odacchi/fcoin-user-manual#31]
直近15個を11個にすれば基本的によさそうだけど、
noteのこの記事もアップグレードが必要かなと。

https://note.mu/fcoinfanjapanese/n/ne59cd48cc711

**Comment by Odacchi** [comment]
トリセツの記事内は、日本語も中国語もともに15を11にひとまず対応しました。

**Comment by Odacchi** [comment]
そもそもリンクを消すことにします。

以下の翻訳をお願いできますか？

---

現在価格に最も近い買いと売りの注文、また、注文金額が大きいほどマイニングの効率が高くなります。

**Comment by GSHT007** [comment]
これ結構正式な中国語難易度高いのでKOUさんYOUさんにお願いしたいです・・・
私生活絶対使わないw

**Comment by Odacchi** [comment]
間違いないｗ

**Comment by BlueKanbu** [comment]
买卖挂单越接近最新价格、订单金额越大，则挖矿效率越高。

需要注意的是，排序挖矿在每天24点（GMT+8）会充值，因此如果想要继续挖矿的话，需要每天24点之后重新挂单。

**Comment by BlueKanbu** [comment]
確かに、日本語に翻訳する時も辛かったですw。
では、お願いします。

**Comment by YOUFCoin** [comment]
お疲れ様です

**Comment by Odacchi** [comment]
反映しました！クローズします
