### ISSUE TITLE
リンク集にコインリンカーのリンクを追加する

### ISSUE THREAD

**Issue by BlueKanbu** [Odacchi/fcoin-user-manual#33]
日本語：
FTパブリックチェーンのスーパーノード候補：
コインリンカー（CoinLinker） (http://coinlinker.io/)

**Comment by BlueKanbu** [comment]
中国語：

**Comment by BlueKanbu** [comment]
お願いします

**Comment by Odacchi** [comment]
アップ完了！

中国語：  
https://www.fcoin-manual.com/link.html

日本語：  
https://www.fcoin-manual.com/cn/link.html

**Comment by Odacchi** [comment]
アップしたのでクローズします。
