### ISSUE TITLE
マイニングページ中国語訳バージョン作成（Youさんと一緒に）

### ISSUE THREAD

**Issue by KouBT** [Odacchi/fcoin-user-manual#5]
今はabout_miningを訳している

**Comment by Odacchi** [comment]
ありがとう！！

**Comment by Odacchi** [comment]
アップロードしたので、チェックしてみてください！
おかしいところとか気になるところあれば、コメントよろしく！

https://www.fcoin-manual.com/cn/about-mining.html

**Comment by Odacchi** [comment]
画像内の文言の翻訳もほしいかも！（すぐにはちょっと対応できないですが

**Comment by YOUFCoin** [comment]
かしこです！

**Comment by YOUFCoin** [comment]
ロックアップマイニングのところで「の」が残ってるw

**Comment by YOUFCoin** [comment]
半減期の通訳文章で、初句の通訳を修正しました！

**Comment by YOUFCoin** [comment]
正解：在挖矿中，每个周期（三个月）就会有一个半减期，以此来逐步减少挖矿的总产量。

**Comment by KouBT** [comment]
> 画像内の文言の翻訳もほしいかも！（すぐにはちょっと対応できないですが

やるよ

**Comment by Odacchi** [comment]
とりあえずYOUさん指摘分を修正
https://github.com/Odacchi/fcoin-user-manual/commit/899598762f9047ed4f4961617d028a7dff35f753

**Comment by Odacchi** [comment]
残タスクは画像の入れ替え

**Comment by YOUFCoin** [comment]
> > 画像内の文言の翻訳もほしいかも！（すぐにはちょっと対応できないですが
> 
> やるよ

もうやった

**Comment by Odacchi** [comment]
こちらも更新対応完了したため一旦クローズ

リファマイニングやその他の課題は別のissueで対応します。
