### ISSUE TITLE
出金の仕方をまとめる

### ISSUE THREAD

**Issue by Odacchi** [Odacchi/fcoin-user-manual#6]
キャプチャー画像つきで
noteにまとめてもらったらいいかも！

よくある質問ページからリンクを貼って対応します！

Fund passwordを設定していない人向けにFund passwordの設定の仕方からあると完璧です！

**Comment by YOUFCoin** [comment]
画像ついたら非常に助かります！

**Comment by KouBT** [comment]
確かに、Fund passwordについての質問が頻発っすね

**Comment by Odacchi** [comment]
よくある質問ページに追加したのでクローズします。

関連チケット：
https://github.com/Odacchi/fcoin-user-manual/issues/7
